API/config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    namespace :v1 do
      resources :bus_positions, :only => [] do
        collection do
          get :statistics
          get :line_history
          get :bus_history
          get :on_radius
          get :with_line_stops_and_positions
          get :with_line_stops_positions_and_speed_avg
        end
      end

      resources :line_positions, :only => [] do
        collection do
          get :from_line
          get :with_stops
        end
      end
      resources :line_stops, :only => [] do
        collection do
          get :from_line
        end
      end
      resources :line_bounding_box, :only => [] do
        collection do
          get :from_line
        end
      end
    end
  end
  resources :line_stops, :only => [:index]
  resources :sys_configs, :only => [:edit, :update]
  resources :line_positions, :only => [:index]
  resources :heat_maps, :only => [] do
    collection do
      get :position
      get :speed
    end
  end
  get '/statistics', :to => 'statistics#index', :as => 'statistics'

  root 'heat_maps#position'

end

API/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "BusData" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>


    <%= javascript_include_tag "application"%>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">BusData</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Statistics", statistics_path  %></li>
            <li><%= link_to "Line Positions", line_positions_path  %></li>
            <!--<li><%#= link_to "Line Stops", line_stops_path  %></li>-->
            <li><%= link_to "Positions Heat Map", position_heat_maps_path  %></li>
            <li><%= link_to "Speed Heat Map", speed_heat_maps_path  %></li>
            <li><%= link_to "Configuration", edit_sys_config_path(1)  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer style="margin-top: 20px">
        <p>&copy; Universidade Federal Fluminense 2016</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>